# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c793c695531588a21983f619ce1612aab52fa0ae8058a4bff2726ed3e25dbb6e0845dc807d795bd8221b76a8e150b563bf41767de1037b79890ede365d7566d

test:
  secret_key_base: a0dcad6c6dc03e5496ca5ba08ab7b4066d152856a672dfbfbfadc0ef4be0d8e8495519fbdd9535c004afd7c7b5a60aa82d4e92f5ad134813eb1d344e4e36d1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
